### ISSUE TITLE
go: error loading module requirements

### ISSUE THREAD

**Issue by dtcokr** [lucaslorentz/caddy-docker-proxy#123] opened 2019-08-25 03:36 UTC
I came across this issue when building a docker image from caddy source code.

### here's the Dockerfile
```
FROM golang:1.12.9-alpine as builder

ENV GO111MODULE=on

RUN apk add --no-cache --update git 

COPY plugin.go /go/caddy/plugin.go

RUN cd caddy \
  && go mod init caddy \
  && go get github.com/caddyserver/caddy \
  && go build
```

### here's the plugin.go
```
package main

import (
		"github.com/caddyserver/caddy/caddy/caddymain"

		// plug in plugins here, for example:
		// _ "import/path/here"

		// http.ipfilter
		_ "github.com/pyed/ipfilter"
		// http.git
		_ "github.com/abiosoft/caddy-git"
		// http.nobots
		_ "github.com/Xumeiquer/nobots"
		// http.realip
		_ "github.com/captncraig/caddy-realip"
                // docker
                _ "github.com/lucaslorentz/caddy-docker-proxy/plugin"
)

func main() {
		caddymain.EnableTelemetry = false
		caddymain.Run()
}
```

### here's the building log
```
Sending build context to Docker daemon    130kB
Step 1/16 : FROM golang:1.12.9-alpine as builder
 ---> e0d646523991
Step 2/16 : ENV GO111MODULE=on
 ---> Running in c7d9838c8468
Removing intermediate container c7d9838c8468
 ---> 51181bd6b365
Step 3/16 : RUN apk add --no-cache --update git
 ---> Running in d639d99d297a
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
(1/5) Installing nghttp2-libs (1.39.2-r0)
(2/5) Installing libcurl (7.65.1-r0)
(3/5) Installing expat (2.2.7-r0)
(4/5) Installing pcre2 (10.33-r0)
(5/5) Installing git (2.22.0-r0)
Executing busybox-1.30.1-r2.trigger
OK: 21 MiB in 20 packages
Removing intermediate container d639d99d297a
 ---> 11bd06afa804
Step 4/16 : COPY plugin.go /go/caddy/plugin.go
 ---> d080ba852a1d
Step 5/16 : RUN cd caddy   && go mod init caddy   && go get github.com/caddyserver/caddy   && go build
 ---> Running in 2a9bc84f337f
go: creating new go.mod: module caddy
go: finding github.com/caddyserver/caddy v1.0.3
go: finding github.com/jimstudt/http-authentication v0.0.0-20140401203705-3eca13d6893a
go: finding github.com/hashicorp/go-syslog v1.0.0
go: finding github.com/naoina/toml v0.1.1
go: finding github.com/naoina/go-stringutil v0.1.0
go: finding github.com/dustin/go-humanize v1.0.0
go: finding github.com/klauspost/cpuid v1.2.0
go: finding github.com/lucas-clemente/quic-go v0.10.2
go: finding github.com/kylelemons/godebug v0.0.0-20170820004349-d65d576e9348
go: finding github.com/flynn/go-shlex v0.0.0-20150515145356-3f9db97f8568
go: finding github.com/mholt/certmagic v0.6.2-0.20190624175158-6a42ef9fe8c2
go: finding github.com/google/uuid v1.1.1
go: finding github.com/BurntSushi/toml v0.3.1
go: finding github.com/go-acme/lego v2.5.0+incompatible
go: finding github.com/marten-seemann/qtls v0.2.3
go: finding github.com/cheekybits/genny v0.0.0-20170328200008-9127e812e1e9
go: finding golang.org/x/net v0.0.0-20190328230028-74de082e2cca
go: finding gopkg.in/mcuadros/go-syslog.v2 v2.2.1
go: finding gopkg.in/natefinch/lumberjack.v2 v2.0.0
go: finding gopkg.in/yaml.v2 v2.2.2
go: finding github.com/gorilla/websocket v1.4.0
go: finding github.com/lucas-clemente/quic-clients v0.1.0
go: finding golang.org/x/crypto v0.0.0-20190228161510-8dd112bcdc25
go: finding gopkg.in/square/go-jose.v2 v2.2.2
go: finding github.com/lucas-clemente/quic-go-certificates v0.0.0-20160823095156-d2f86524cced
go: finding github.com/golang/mock v1.2.0
go: finding golang.org/x/text v0.3.0
go: finding github.com/onsi/gomega v1.5.0
go: finding github.com/lucas-clemente/aes12 v0.0.0-20171027163421-cd47fb39b79f
go: finding github.com/stretchr/testify v1.3.0
go: finding github.com/russross/blackfriday v0.0.0-20170610170232-067529f716f4
go: finding github.com/onsi/ginkgo v1.8.0
go: finding golang.org/x/sync v0.0.0-20181221193216-37e7f081c4d4
go: finding golang.org/x/sys v0.0.0-20190124100055-b90733256f2e
go: finding golang.org/x/net v0.0.0-20180906233101-161cd47e91fd
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding github.com/cenkalti/backoff v2.1.1+incompatible
go: finding golang.org/x/sys v0.0.0-20190228124157-a34e9553db1e
go: finding gopkg.in/yaml.v2 v2.2.1
go: finding github.com/miekg/dns v1.1.3
go: finding golang.org/x/sys v0.0.0-20180909124046-d0be0721c37e
go: finding golang.org/x/net v0.0.0-20190125091013-d26f9f9a57f3
go: finding gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: finding gopkg.in/fsnotify.v1 v1.4.7
go: finding github.com/hpcloud/tail v1.0.0
go: finding github.com/stretchr/objx v0.1.0
go: finding github.com/fsnotify/fsnotify v1.4.7
go: finding github.com/davecgh/go-spew v1.1.0
go: finding github.com/hashicorp/golang-lru v0.0.0-20180201235237-0fb14efe8c47
go: finding golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f
go: finding golang.org/x/crypto v0.0.0-20190123085648-057139ce5d2b
go: finding github.com/onsi/ginkgo v1.6.0
go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: finding github.com/bifurcation/mint v0.0.0-20180715133206-93c51c6ce115
go: finding github.com/golang/protobuf v1.2.0
go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
go: downloading github.com/caddyserver/caddy v1.0.3
go: extracting github.com/caddyserver/caddy v1.0.3
go: downloading github.com/google/uuid v1.1.1
go: extracting github.com/google/uuid v1.1.1
go: downloading github.com/mholt/certmagic v0.6.2-0.20190624175158-6a42ef9fe8c2
go: downloading github.com/flynn/go-shlex v0.0.0-20150515145356-3f9db97f8568
go: extracting github.com/flynn/go-shlex v0.0.0-20150515145356-3f9db97f8568
go: extracting github.com/mholt/certmagic v0.6.2-0.20190624175158-6a42ef9fe8c2
go: downloading github.com/go-acme/lego v2.5.0+incompatible
go: downloading github.com/klauspost/cpuid v1.2.0
go: extracting github.com/klauspost/cpuid v1.2.0
go: downloading golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: extracting golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: extracting github.com/go-acme/lego v2.5.0+incompatible
go: downloading gopkg.in/square/go-jose.v2 v2.2.2
go: downloading github.com/miekg/dns v1.1.3
go: downloading github.com/cenkalti/backoff v2.1.1+incompatible
go: downloading golang.org/x/net v0.0.0-20190328230028-74de082e2cca
go: extracting github.com/cenkalti/backoff v2.1.1+incompatible
go: extracting gopkg.in/square/go-jose.v2 v2.2.2
go: extracting golang.org/x/net v0.0.0-20190328230028-74de082e2cca
go: downloading golang.org/x/text v0.3.0
go: extracting github.com/miekg/dns v1.1.3
go: downloading golang.org/x/sys v0.0.0-20190228124157-a34e9553db1e
go: extracting golang.org/x/sys v0.0.0-20190228124157-a34e9553db1e
go: extracting golang.org/x/text v0.3.0
go: downloading gopkg.in/natefinch/lumberjack.v2 v2.0.0
go: downloading github.com/jimstudt/http-authentication v0.0.0-20140401203705-3eca13d6893a
go: downloading github.com/russross/blackfriday v0.0.0-20170610170232-067529f716f4
go: downloading github.com/hashicorp/go-syslog v1.0.0
go: downloading github.com/gorilla/websocket v1.4.0
go: extracting github.com/hashicorp/go-syslog v1.0.0
go: extracting github.com/jimstudt/http-authentication v0.0.0-20140401203705-3eca13d6893a
go: finding github.com/pyed/ipfilter v1.1.4
go: finding github.com/abiosoft/caddy-git latest
go: finding github.com/captncraig/caddy-realip latest
go: finding github.com/lucaslorentz/caddy-docker-proxy/plugin latest
go: finding github.com/Xumeiquer/nobots v0.1.1
go: extracting github.com/russross/blackfriday v0.0.0-20170610170232-067529f716f4
go: downloading github.com/lucas-clemente/quic-go v0.10.2
go: downloading github.com/dustin/go-humanize v1.0.0
go: extracting github.com/gorilla/websocket v1.4.0
go: downloading gopkg.in/yaml.v2 v2.2.2
go: downloading github.com/naoina/toml v0.1.1
go: extracting github.com/dustin/go-humanize v1.0.0
go: downloading github.com/abiosoft/caddy-git v0.0.0-20190703061829-f8cc2f20c9e7
go: finding github.com/lucaslorentz/caddy-docker-proxy v0.3.1
go: downloading github.com/captncraig/caddy-realip v0.0.0-20190710144553-6df827e22ab8
go: downloading github.com/pyed/ipfilter v1.1.4
go: downloading github.com/Xumeiquer/nobots v0.1.1
go: downloading github.com/lucaslorentz/caddy-docker-proxy v0.3.1
go: extracting github.com/captncraig/caddy-realip v0.0.0-20190710144553-6df827e22ab8
go: extracting github.com/abiosoft/caddy-git v0.0.0-20190703061829-f8cc2f20c9e7
go: extracting github.com/Xumeiquer/nobots v0.1.1
go: extracting github.com/lucaslorentz/caddy-docker-proxy v0.3.1
go: extracting github.com/naoina/toml v0.1.1
go: downloading github.com/naoina/go-stringutil v0.1.0
go: extracting github.com/lucas-clemente/quic-go v0.10.2
go: downloading github.com/bifurcation/mint v0.0.0-20180715133206-93c51c6ce115
go: downloading github.com/hashicorp/golang-lru v0.0.0-20180201235237-0fb14efe8c47
go: downloading github.com/lucas-clemente/quic-go-certificates v0.0.0-20160823095156-d2f86524cced
go: downloading github.com/cheekybits/genny v0.0.0-20170328200008-9127e812e1e9
go: extracting github.com/naoina/go-stringutil v0.1.0
go: downloading github.com/lucas-clemente/aes12 v0.0.0-20171027163421-cd47fb39b79f
go: extracting github.com/hashicorp/golang-lru v0.0.0-20180201235237-0fb14efe8c47
go: extracting github.com/cheekybits/genny v0.0.0-20170328200008-9127e812e1e9
go: extracting github.com/bifurcation/mint v0.0.0-20180715133206-93c51c6ce115
go: extracting github.com/pyed/ipfilter v1.1.4
go: extracting github.com/lucas-clemente/aes12 v0.0.0-20171027163421-cd47fb39b79f
go: extracting github.com/lucas-clemente/quic-go-certificates v0.0.0-20160823095156-d2f86524cced
go: extracting gopkg.in/yaml.v2 v2.2.2
go: extracting gopkg.in/natefinch/lumberjack.v2 v2.0.0
go: finding github.com/oschwald/maxminddb-golang v1.3.0
go: finding github.com/caddyserver/caddy v1.0.1
go: finding github.com/docker/go-connections v0.4.0
go: finding github.com/pquerna/cachecontrol v0.0.0-20180517163645-1555304b9b35
go: finding github.com/opencontainers/image-spec v1.0.1
go: finding github.com/containerd/containerd v1.2.7
go: finding github.com/docker/distribution v2.7.1+incompatible
go: finding github.com/stretchr/testify v1.4.0
go: finding github.com/caddyserver/dnsproviders v0.3.0
go: finding gotest.tools v2.2.0+incompatible
go: finding github.com/opencontainers/go-digest v1.0.0-rc1
go: finding github.com/docker/docker v0.7.3-0.20190816182709-c9aee96bfd1b
go: finding github.com/Microsoft/go-winio v0.4.14
go: finding github.com/morikuni/aec v0.0.0-20170113033406-39771216ff4c
go: finding github.com/nicolasazrak/caddy-cache v0.3.4
go: finding github.com/docker/go-units v0.4.0
go: finding github.com/Azure/go-ansiterm v0.0.0-20170929234023-d6e3b3328b78
go: finding github.com/decker502/dnspod-go v0.0.0-20181231011336-d1081970f528
go: finding github.com/google/go-querystring v1.0.0
go: finding github.com/dnsimple/dnsimple-go v0.23.0
go: finding github.com/exoscale/egoscale v0.17.0
go: finding github.com/pkg/errors v0.8.1
go: finding github.com/modern-go/reflect2 v1.0.1
go: finding github.com/nrdcg/auroradns v1.0.0
go: finding google.golang.org/api v0.3.2
go: finding github.com/cloudflare/cloudflare-go v0.8.5
go: finding golang.org/x/sys v0.0.0-20190507160741-ecd444e8653b
go: finding github.com/juju/ratelimit v1.0.1
go: finding github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190703055746-de62006faf99
go: finding github.com/fatih/structs v1.1.0
go: finding github.com/Azure/go-autorest/autorest/azure/auth v0.1.0
go: finding github.com/h2non/gock v0.0.0-00010101000000-000000000000
go: finding github.com/Azure/go-autorest/autorest/validation v0.1.0
go: finding github.com/go-ini/ini v1.42.0
go: finding github.com/sirupsen/logrus v1.4.1
go: finding github.com/timewasted/linode v0.0.0-20160829202747-37e84520dcf7
go: finding github.com/json-iterator/go v1.1.6
go: github.com/h2non/gock@v0.0.0-00010101000000-000000000000: unknown revision 000000000000
go: finding github.com/nrdcg/goinwx v0.6.0
go: finding github.com/JamesClonk/vultr v2.0.0+incompatible
go: finding github.com/gofrs/uuid v3.2.0+incompatible
go: finding golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: finding github.com/kolo/xmlrpc v0.0.0-20190514182600-74b23a09d7ea
go: finding github.com/namedotcom/go v0.0.0-20180403034216-08470befbe04
go: finding github.com/linode/linodego v0.10.0
go: finding github.com/akamai/AkamaiOPEN-edgegrid-golang v0.7.4
go: finding github.com/cpu/goacmedns v0.0.1
go: finding github.com/mitchellh/mapstructure v1.1.2
go: finding github.com/ovh/go-ovh v0.0.0-20181109152953-ba5adb4cf014
go: finding github.com/transip/gotransip v5.8.2+incompatible
go: finding gopkg.in/ns1/ns1-go.v2 v2.0.0-20190322154155-0dafb5275fd1
go: finding github.com/Azure/azure-sdk-for-go v31.0.0+incompatible
go: finding github.com/Azure/go-autorest/autorest/to v0.1.0
go: finding github.com/aws/aws-sdk-go v1.19.15
go: error loading module requirements
The command '/bin/sh -c cd caddy   && go mod init caddy   && go get github.com/caddyserver/caddy   && go build' returned a non-zero code: 1
```

### docker version
`Docker version 19.03.1, build 74b1e89`

### os info
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

`kernel 4.14.129`

**Comment by lucaslorentz** [comment] 2019-08-25 19:21
It seems that the problem is that we have only one go module containing:
- plugin for caddy (which depends only on docker package)
- our own caddy distribution (which depends also on other plugins)
  https://github.com/lucaslorentz/caddy-docker-proxy/blob/master/main.go#L12

Even though you import only our caddy plugin, it will try to resolve and download all dependencies from our own caddy distribution.

I'm trying to isolate those into 2 separate go modules.

**Comment by lucaslorentz** [comment] 2019-08-25 19:29
Fixed by this commit: https://github.com/lucaslorentz/caddy-docker-proxy/commit/add5f834ffa0ad71e8e7bf4ef3200052d1619a26
I've also added a new release version: v0.3.2

I was able to build v0.3.2 using the caddyfile you provided.
Caddy build server also was able to build v0.3.2.

Thanks for reporting this

**Closed** 2019-08-25 19:33 UTC
