### ISSUE TITLE
Using respond directive as single string arg fails

### ISSUE THREAD

**Issue by polarathene** [lucaslorentz/caddy-docker-proxy#283] opened 2021-08-11 00:38 UTC
I have CDP working well as a reverse proxy to other containers, but when trying to make a dummy container I seem to be unable to get a basic [`respond` directive](https://caddyserver.com/docs/caddyfile/directives/respond) to work:

```
labels:
  caddy: example.com
  caddy.respond: "Hello, world!"
```

This seems to have no effect on the CDP container itself or another container. Meanwhile if I assign the ENV `CADDY_DOCKER_CADDYFILE_PATH` to the CDP container for a Caddyfile to use and add:

```
example.com {
  respond "Hello, world!"
}
```

It works perfectly fine?

Is there some syntax I am missing here to get it to work with the label approach?

**Comment by polarathene** [comment] 2021-08-11 00:53
This was user error. I was under the impression I could use `stop` and `start` or `restart` commands with `docker-compose` on the CDP container to "refresh" it's yml config for labels like I was doing when updating the `Caddyfile`. Instead I need to recreate the container with `docker-compose up -d`.

**Comment by polarathene** [comment] 2021-08-11 01:42
I have noticed that the syntax used doesn't work unless matching [the syntax shown in the README](https://github.com/lucaslorentz/caddy-docker-proxy#tokens-and-arguments) that begins with a matcher first.

If the value has a space in it, then the first part is used as a route matcher, eg `"/hello world"` is equivalent to `/hello "world"` not `* "hello world"`.

Is this a gotcha to be aware of with CDP label vs Caddyfile? I assume it's due to starting my value with double quotes, not as a later arg value? Perhaps the README could be updated to clarify this gotcha?

**Comment by francislavoie** [comment] 2021-08-11 04:30
The issue is that `"` double quotes have meaning in both yaml and in Caddyfile. The easy fix is to use backticks (`) instead in labels. https://caddyserver.com/docs/caddyfile/concepts#tokens-and-quotes

**Comment by francislavoie** [comment] 2021-08-12 06:43
This is already mentioned in the README, so I'll close this https://github.com/lucaslorentz/caddy-docker-proxy#tokens-and-arguments

**Closed by francislavoie** 2021-08-12 06:43 UTC

**Comment by polarathene** [comment] 2021-08-12 10:12
> This is already mentioned in the README

> *If you need whitespace or line-breaks inside one of the arguments, use double-quotes or backticks around it:*

And along with the examples of `respond`, you might misunderstand like I did with thinking `respond: "Hello World"` would work, double-quotes are used, which the statement above states should cover whitespace in an argument.

I think while minor, it might be worth mentioning the gotcha there, perhaps with that single arg `respond` example for context?
